### PR TITLE
add two functions for inc and dec a gauge

### PR DESCRIPTION
**Pull request by jgrodziski**
add two functions `inc-gauge` and `dec-gauge` that increment and decrement a gauge metric mirroring the java API.

### CODE REVIEW

**Comment by hiram-madelaine** [comment]
Hi ! 
I am very interested by this pull request.
Is it possible to merge it ?
Thank very much

**Comment by hantuzun** [comment]
I'd like to see this merge too

**Comment by beorn7** [comment]
Sorry, folks, for the staleness here. The main contributor has left SoundCloud quite some time ago. @grobie: You touched this last. Do you have an opinion how to proceed with this PR in particular and with the repo in general?

**Comment by grobie** [comment]
Years later I see this PR again :see_no_evil:

SoundCloud has stopped using Clojure many years ago. I guess it would make most sense to transfer this repository to a new owner, potentially in the https://github.com/prometheus-community/ organization. @hantuzun @atsman @jgrodziski I understand it has been years, but would anyone of you be interested in that?

**Comment by alehatsman** [comment]
Hey @grobie, prometheus-community would be a good spot for that, what is needed in order to move it? I guess this repo needs to be archived and a new one created in the prometheus-community org. Anything else?

**Comment by grobie** [comment]
@atsman as a Prometheus team member, I'm happy to shepherd the migration of the repository. I do have the permissions in both organization to organize an owner change. What's really needed here is some commitment from someone interested to act as maintainer of the project. Commits rights will be provided.

**Comment by alehatsman** [comment]
@grobie well ok, I gave it some thought last evening and think I can commit to maintaining it. Please transfer repo and provide me with commit rights.

**Comment by grobie** [comment]
Thanks a lot for offering your help here @atsman! Please note it'll take a few days to organize everything. Both SoundCloud's management + other prometheus maintainers have to approve, but I hope to push it through this week.
.

**Comment by alehatsman** [comment]
Hey @grobie, sounds good! No hurry here, ping me when there will be some progress and I will assist

**Comment by grobie** [comment]
Hey @atsman. I have general approvals from SoundCloud, but I fear I won't be able to get this done before my vacation starts on Saturday. Maybe @beorn7 or @superq can help paving the way from the Prometheus side, otherwise I fear this will have to wait until August.

**Comment by alehatsman** [comment]
Hey @grobie, sounds pity, like we can forget about this one for years again.

Guys, @beorn7, @SuperQ please assist here if you can :)

@grobie enjoy your vacation!

**Comment by beorn7** [comment]
@SuperQ is definitely better suited than myself to guide the transition to prometheus-community.

**Comment by alehatsman** [comment]
I also found one more library which seems more maintained than this one, so not sure if it still makes sense to continue any work on this one. https://github.com/clj-commons/iapetos

**Comment by grobie** [comment]
Hey @atsman, that's great news I guess. I just checked and they wrapper
it's already linked from the official Prometheus page (although not on the
client library page)
https://prometheus.io/docs/instrumenting/exporters/#other-third-party-utilities

I'll make a note in this repo when I'm back at work and archive it.

**Comment by grobie** [comment]
I added a note about the project status to the readme https://github.com/soundcloud/prometheus-clj/commit/f56c78c6dbc3feb7c4974327d93ed78173faa7d1. I'll archive this repository now. Good luck everyone.

**Pull request closed without merging**
